<?php

/**
 * @file
 * Contains book_catalogue_import.module.
 */

use Drupal\Core\Routing\RouteMatchInterface;

/**
 * Implements hook_help().
 */
function book_catalogue_import_help($route_name, RouteMatchInterface $route_match) {
  switch ($route_name) {
    // Main module help for the book_catalogue_import module.
    case 'help.page.book_catalogue_import':
      $output = '';
      $output .= '<h3>' . t('About') . '</h3>';
      $output .= '<p>' . t('Import book catalogue') . '</p>';
      return $output;

    default:
  }
}
